# Dependencies
markdown:           kramdown 
highlighter:        rouge

# Permalinks
permalink:           pretty

# Setup
title:               Theed - Machine Learning for Smart City
tagline:             "machine learning"
description:         'Machine Learning Course'
url:                 https://theed.ml
baseurl:             ''
paginate:            20
# paginate_path:       "/blog/page:num/"

# About/contact
author:
  name:              Alessandro Leite
  url:               https://twitter.com/alessandroleite
  email:             hello[at]theed[dot]ml

# Optional features
google_analytics_id: G-HT5F7FLE2L
google_analytics: G-HT5F7FLE2L

# Source vars
version:             0.6.0
github:              "https://github.com/theed-ml"
repo:                "https://github.com/theed-ml/theed-ml.github.io"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap


# Collections
collections:
  - posts

# Pagination Configuration
paginate: 5
paginate_path: "/page/:num/"

# Page Listing
# pages_list:
#   About:             /about
#   Archive:           /archive
#   Tags:              /tags
#   Feed:              /atom.xml
#   Site Information:  /site


# Custom vars
version:          1.0.0
categorylist:     [machine learning, support vector machine, linear regression, principal component analysis, decision trees, deep learning, k-means, neural networks]
collections:
    notes:
        collections_dir: notes
        output: true
permalink: /notes/:name
  
  
  # Github flavored markdown
markdown: kramdown
kramdown:
  auto_ids:      true
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  input:         GFM
  hard_wrap:     false
  footnote_nr:   1
  show_warnings: false
